version: '3.1'

services:
  user:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest
      MYSQL_USER: rest
      MYSQL_PASSWORD: rest
    ports:
      - 3306:3306
  order1:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_USER: order
      MYSQL_PASSWORD: order
    ports:
      - 3307:3306
  order2:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_USER: order
      MYSQL_PASSWORD: order
    ports:
      - 3308:3306
    